## Containers parameters shared between processing and webApp
##
## Author: Raymond Ehlers <raymond.ehlers@cern.ch>, Yale University

# Set debug
debug: false

#: List of subsystems.
#: Each subsystem listed here will have an individual page for their respective histograms.
#: The HLT _MUST_ be included here!
# By using set, we
subsystemList: &subsystemList
    - "EMC"
    - "TPC"
    - "HLT"

#: Each of these subsystems will also get an individual page for access to their respective ROOT files.
subsystemsWithRootFilesToShow: *subsystemList

#: Select whether to enable trending
trending: true

# Folders
#: The name of the static folder on the disk.
staticFolder: &staticFolder "static"

#: The name of the data folder on the disk.
dataFolder: &dataFolder "data"

#: The name of the templates folder on the disk.
templateFolder: &templateFolder "templates"

#: The path to the database.
databaseLocation: !joinPaths
    - "file://"
    - *dataFolder
    - "overwatch.fs"

#: The file extension to use when printing ROOT files.
fileExtension: "png"

#: Set the logging level
loggingLevel: "INFO"
